### PR TITLE
Make old weather data accessable via the constructor.

### PR DESCRIPTION
**Pull request by 1kastner**
Make old weather data accessable via the constructor.

### CODE REVIEW

**Comment by BenKester** [comment]
@1kastner , can you give an example of how to use your update? I can't figure out what to pass to time_url.

**Comment by 1kastner** [comment]
Well you might be aware that at
https://github.com/1kastner/forecastiopy3/blob/0b83083bdf7113366a67848575220c80dbdea1b4/forecastiopy/ForecastIO.py
Line 32 there is already an attribute time_url - I just used that one.
The only issue was that so far it was not easily possible to assign a
value to that field. That value is used again in line 123-124 and allows
you to access data from the past. As it is a string operation, you need
to check the API documentation. I deleted the code I used during that
period as the project was over.

**Comment by 1kastner** [comment]
@bitpixdigital Any plans to merge this?

**Comment by 1kastner** [comment]
Thanks :)

**Comment by bitpixdigital** [comment]
No problem. Thank you for the contribution. Apologies for taking so long to merge!

**Pull request merged**
